# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:
let
  hostname = "alice";
  username = "alice";
  getNixFiles = import ./modules/functions/getNixFiles.nix;
  filesToImport =
    getNixFiles {
      path = ./modules/system/${hostname};
      inherit lib;
    }
    ++ getNixFiles {
      path = ./modules/system/shared;
      inherit lib;
    };
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ./sops.nix
  ]
  ++ filesToImport;

  config = {
    tools.lidswitch = {
      enable = false;
    };
    tools.android = {
      enable = false;
      username = username;
      enableAndroidStudio = false;
    };
    tools.networking = {
      enable = true;
      hostname = hostname;
      enableIwdWifi = false;
    };
    cloud.nextcloud.client.upload.enable = true;
    custom.containers.docker = {
      enable = false;
    };

    nixpkgs.config.permittedInsecurePackages = [
      "python3.13-ecdsa-0.19.1"
    ];

    boot = {
      kernelParams = [ "psmouse.synaptics_intertouch=0" ];
      # kernelPackages = pkgs.linuxKernel.packages.linux_zen;
      initrd.luks.devices."luks-dd6eaf2f-503c-468e-9dd6-b093c8cbcf6f".device =
        "/dev/disk/by-uuid/dd6eaf2f-503c-468e-9dd6-b093c8cbcf6f";
    };

    fileSystems."/drives/data" = {
      device = "/dev/mapper/luks-58149879-604e-4b89-b208-e5a4d86f3336";
      fsType = "ext4";
      options = [ "defaults" ];
    };

    i18n.supportedLocales = [
      "en_GB.UTF-8/UTF-8"
      "en_US.UTF-8/UTF-8"
    ];

    #NodeJS
    # programs.npm.enable = true;

    services.upower.enable = true;

    # SAMBA
    services.gvfs.enable = true;

    # Enable sound.
    hardware.bluetooth = {
      enable = true;
      powerOnBoot = true;
    };
    services.pipewire = {
      enable = true;
      # alsa.enable = true;
      # pulse.enable = true;
      wireplumber.enable = true;
      # If you want to use JACK applications, uncomment this
      jack.enable = true;
    };

    services.udisks2.enable = true;

    system.stateVersion = "24.11"; # Did you read the comment?
  };
}
