# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  pkgs,
  modulesPath,
  ...
}:
let
  hostname = "alice";
  getNixFiles = import ./modules/functions/getNixFiles.nix;
  filesToImport =
    getNixFiles {
      path = ./modules/system/${hostname};
      inherit lib;
    }
    ++ getNixFiles {
      path = ./modules/system/shared;
      inherit lib;
    };
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ./sops.nix
  ] ++ filesToImport;

  boot = {
    kernelParams = [ "psmouse.synaptics_intertouch=0" ];
    # kernelPackages = pkgs.linuxKernel.packages.linux_zen;
  };

  fileSystems."/drives/data" = {
    device = "/dev/disk/by-uuid/0f9c03b0-f351-4ccd-8a05-e2ec8a29d1e7";
    fsType = "ext4";
    options = [ "defaults" ];
  };

  services.xserver.videoDrivers = [ "nouveau" ];

  networking = {
    # firewall.allowedTCPPorts = [];
    # firewall.allowedUDPPorts = [];
    hostName = hostname;
    # networkmanager.enable = lib.mkForce false;
    # wireless.iwd.enable = true;
    # networkmanager.wifi.backend = "iwd";
    networkmanager.wifi.powersave = false;
    networkmanager.wifi.scanRandMacAddress = false;

    # wireless.enable = true;
    firewall.enable = true;
  };

  xdg = {
    portal = {
      xdgOpenUsePortal = true;
      enable = true;
      wlr.enable = true;
      extraPortals = [
        pkgs.xdg-desktop-portal-wlr
        pkgs.xdg-desktop-portal-gtk
      ];
      configPackages = [ pkgs.sway ];
    };
  };

  # Android
  programs.adb.enable = true;

  #NodeJS
  # programs.npm.enable = true;

  # services.upower.enable = true;

  # SAMBA
  services.gvfs.enable = true;

  # Fonts
  fonts.packages = with pkgs; [
    font-awesome
    font-awesome_5
    font-awesome_4
    powerline-fonts
    powerline-symbols
    dejavu_fonts
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-emoji
    nerd-fonts.zed-mono
    open-sans
  ];

  # Enable sound.
  hardware.bluetooth.enable = true;
  services.blueman.enable = true;
  services.pipewire = {
    enable = true;
    # alsa.enable = true;
    # pulse.enable = true;
    wireplumber.enable = true;
    # If you want to use JACK applications, uncomment this
    # jack.enable = true;
  };

  services.udisks2.enable = true;

  # Virtualization
  # virtualisation.libvirtd.enable = true;
  # virtualisation.docker.enable = true;

  system.stateVersion = "23.05"; # Did you read the comment?
}
