# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
let
  hostname = "eve";
  getNixFiles = import ./modules/functions/getNixFiles.nix;
  filesToImport =
    getNixFiles {
      path = ./modules/system/shared;
      inherit lib;
    }
    ++ getNixFiles {
      path = ./modules/system/eve-bob;
      inherit lib;
    }
    ++ getNixFiles {
      path = ./modules/system/eve;
      inherit lib;
    };
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ./sops.nix
  ] ++ filesToImport;

  system.stateVersion = "24.05"; # Did you read the comment?
  networking = {
    firewall.enable = true;
    # firewall.allowedUDPPorts = [];
    hostName = hostname;
  };

  # systemd.services.nextcloud-setup.serviceConfig = {
  #   RequiresMountsFor = [ "/var/lib/nextcloud" ];
  # };
  networking.firewall.allowedTCPPorts = [
    80
    443
  ];
  services.nextcloud = {
    enable = true;
    package = pkgs.nextcloud29;
    # hostName = "eveee.v6.army";
    hostName = "bakarh.ddns.net";
    https = true;
    settings.overwriteprotocol = "https";
    # Let NixOS install and configure the database automatically.
    database.createLocally = true;
    # Let NixOS install and configure Redis caching automatically.
    configureRedis = true;
    # Increase the maximum file upload size to avoid problems uploading videos.
    maxUploadSize = "1G";
    autoUpdateApps.enable = true;
    extraAppsEnable = true;
    extraApps = with config.services.nextcloud.package.packages.apps; {
      # List of apps we want to install and are already packaged in
      # https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/nextcloud/packages/nextcloud-apps.json
      inherit groupfolders;
    };
    config = {
      adminuser = "root";
      adminpassFile = config.sops.secrets."nextcloud/Password".path;
    };
    extraOptions.enabledPreviewProviders = [
      "OC\\Preview\\BMP"
      "OC\\Preview\\GIF"
      "OC\\Preview\\JPEG"
      "OC\\Preview\\Krita"
      "OC\\Preview\\MarkDown"
      "OC\\Preview\\MP3"
      "OC\\Preview\\OpenDocument"
      "OC\\Preview\\PNG"
      "OC\\Preview\\TXT"
      "OC\\Preview\\XBitmap"
      "OC\\Preview\\HEIC"
    ];
  };
  services.nginx.virtualHosts = {
    ${config.services.nextcloud.hostName} = {
      forceSSL = true;
      enableACME = true;
    };
  };
  security.acme = {
    acceptTerms = true;
    certs = {
      ${config.services.nextcloud.hostName}.email = "h.bakardzhiev@gmx.com";
    };
  };

  # External strorage
  fileSystems."/run/media/backup" = {
    device = "/dev/disk/by-uuid/19F41D271DCA2DF1";
    fsType = "ntfs-3g";
    options = [ "defaults" ];
  };
  fileSystems."/run/media/et1" = {
    device = "/dev/disk/by-uuid/D01235C71235B378";
    fsType = "ntfs-3g";
    options = [ "defaults" ];
  };

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "uas"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ca49793c-1ba0-4440-887c-26917bc57c4e";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FFB5-60CA";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/18139836-fda5-4fb0-b5aa-52084d4b8f9b"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
