name: Bump flake.lock

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/install-nix-action@v20

      # Pull the latest changes from the remote branch to avoid non-fast-forward errors
      - run: git pull --rebase origin main

      - run: nix flake update

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump flake.lock
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Bot
          commit_author: Flake Bot <actions@github.com>
          skip_dirty_check: false
          skip_fetch: true
